name: CI-CD

on:
  push:
    branches:
      - new-setup

  pull_request:
    branches:
      - new-setup

permissions:
  contents: read
  id-token: write

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run tests
        run: npm run test


  deploy:
    needs: build-and-test
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::023133287482:role/github-actions-nestjs-deploy-role
          aws-region: ap-south-1

      - name: Deploy to EC2
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "i-0bcc63672446eebb8" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "cd /home/ubuntu/diya-nestjs-crud",
              "git config --global --add safe.directory /home/ubuntu/diya-nestjs-crud",
              "git fetch origin",
              "git reset --hard origin/new-setup",
              "npm ci",
              "npm run build"
            ]' \
            --query "Command.CommandId" \
            --output text)

          echo "SSM Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "i-0bcc63672446eebb8"

          echo "Deployment completed successfully."